version: "3.8"
services:
  my-react-app:
    container_name: hypertube_fromtend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./my-react-app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"